name: telegram notifications
on:
  pull_request:
    types: [opened, reopened]
jobs:

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: send telegram message on created pull request
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ğŸš€ ğŸš€ ğŸš€   ${{ github.actor }} created a pull request   ğŸš€ ğŸš€ ğŸš€ 
            1{{ github.payload.action.pull_request.name }}
            2{{ payload.action.pull_request.name }}
            3{{ action.pull_request.name }}
            4{{ github.action.pull_request.name }}
            5{{ payload.action.pull_request.name }}
            
            {{ action.pull_request.description }}
            
            â¬‡ï¸ğŸ‘€â¬‡ï¸ğŸ‘€â¬‡ï¸ğŸ‘€â¬‡ï¸ğŸ‘€â¬‡ï¸ğŸ‘€â¬‡ï¸â¬‡ï¸ğŸ‘€â¬‡ï¸ğŸ‘€â¬‡ï¸
            See changes: https://github.com/${{ github.repository }}/pulls/{{ action.pull_request.id }}

